version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: nodeauth
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres
  # mongodb:
  #   image: mongo:latest
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: docker
  #     MONGO_INITDB_ROOT_PASSWORD: docker
  #     MONGO_INITDB_DATABASE: nodeauth
  #   ports:
  #     - 27017:27017
  # mongoclient:
  #   image: mongoclient/mongoclient
  #   ports:
  #     - 3000:3000
  #   links:
  #     - mongodb
